# ubwl_m40it3_v03_fixed

Generated by [Auto-Keyboard-Design-Kit](https://auto-kdk.pages.dev/)

## Preview

- 3D View

![Case Preview](images/ubwl_m40it3_v03_fixed-case-preview.png)

- Top View

![Top View](images/ubwl_m40it3_v03_fixed-top-view.png)

## Parts List

|Part|Quantity|
|---|---|
|wireless controller|1|
|Conthrough(2.5mm, 9pin)|2|
|Battery|1|
USB-C cable|1|
|MX switch and MX socket|40|
|Diode|40|
|Keycap|40|

